spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost:5432/auth_service}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:31032000}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://${DATABASE_URL:localhost:5432/auth_service}
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:31032000}
server:
  port: ${SERVER_PORT:8080}
